# YAML配置文件示例
app_name: emm-account
version: 1.0.0
author: wgx
encoding-type: utf-8

features:
  - 登录
  - 注册
  - 仪表盘

web:
  header:
    access-token: Authorization-Access-token
    refresh-token: Authorization-Refresh-token

settings:
  analytics: true

storage:
  user-password:
    encryption: SHA-256
    frequency:  2
    # noinspection SpellCheckingInspection
    prefix-salt: sihfdshfoifdhs
    # noinspection SpellCheckingInspection
    suffix-salt: wfnissn
  user-phone:
    encryption: SHA-256
    frequency:  2
    # noinspection SpellCheckingInspection
    prefix-salt: sfoissdff
    # noinspection SpellCheckingInspection
    suffix-salt: wfnissn

server:
  port: 8088
  servlet:
    context-path: /

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mariadb://localhost:3366/emm
    driver-class-name: org.mariadb.jdbc.Driver
    username: emm
    password: emm
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      connection-test-query: SELECT 1
      auto-commit: true

mybatis:
  configuration:  # setting配置
    auto-mapping-behavior: full
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    aggressive-lazy-loading: true

  mapper-locations: classpath:/mapper/*.xml # mapper xml位置

jwt:
  # noinspection SpellCheckingInspection
  secret: ajfojsgineori=esf=-g-=gre--**
  access-token-expire: 1800
  refresh-token-expire: 604800
  algorithm:  HMAC256
  allow-update-refresh-tokens: false

