# YAML配置文件示例
app_name: emm-account
version: 1.0.0
author: wgx
encoding-type: utf-8

features:
  - 登录
  - 注册
  - 仪表盘

web:
  header:
    access-token: Authorization-Access
    refresh-token: Authorization-Refresh
    email-verification-token: Authorization-Email-Verification

settings:
  analytics: true

storage:
  user-password:
    encryption: SHA-256
    frequency:  2
    # noinspection SpellCheckingInspection
    prefix-salt: sihfdshfoifdhs
    # noinspection SpellCheckingInspection
    suffix-salt: wfnissn
  user-phone:
    encryption: SHA-256
    frequency:  2
    # noinspection SpellCheckingInspection
    prefix-salt: sfoissdff
    # noinspection SpellCheckingInspection
    suffix-salt: wfnissn

server:
  port: 8088
  servlet:
    context-path: /

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mariadb://localhost:3366/emm
    driver-class-name: org.mariadb.jdbc.Driver
    username: emm
    password: emm
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      connection-test-query: SELECT 1
      auto-commit: true
  mail:
    # noinspection SpellCheckingInspection
    host: smtp.exmail.qq.com
    port: 465
    username: 
    # noinspection SpellCheckingInspection
    password: 
    test-connection: true
    protocol: smtps
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true #启用SMTP服务器的身份验证，这是为了确保只有合法用户可以发送邮件。
      mail.smtp.starttls.enable: true #启用TLS加密，这是为了确保邮件传输的安全性。
      mail.smtp.starttls.required: true #要求使用TLS加密，如果连接不是通过TLS加密传输，则连接将失败。
  data:
    redis:
      host: localhost
      port: 3288
      password: QB32533

mybatis:
  configuration:  # setting配置
    auto-mapping-behavior: full
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    aggressive-lazy-loading: true

  mapper-locations: classpath:/mapper/*.xml # mapper xml位置
  type-handlers-package: com.emm.mapper.type

jwt:
  # noinspection SpellCheckingInspection
  secret: ajfojsgineori=esf=-g-=gre--**
  access-token-expire: 1800
  refresh-token-expire: 604800
  algorithm:  HMAC256
  allow-update-refresh-tokens: false

verification-code:
  email:
    length: 6
    expire: 300
    prefix-content: 验证码为：
    suffix-content: ，验证码5分钟有效
    url:  http://127.0.0.1:8088

schedule:
  clear-email-verification-code-map-period: 600

data:
  dir:  C:\Users\A7755\Nextcloud\Project\emm-community\emm\emm-account\data
  config:
    permission-config:  \config\permission.json

